-- https://wiki.hypr.land/Configuring/Basics/Autostart/

hl.on("hyprland.start", function()
  hl.exec_cmd("sudo /usr/local/sbin/mute-led")
  hl.exec_cmd("pkill awww-daemon; awww-daemon & sleep 1 && ~/scripts/changeWall rand")
  hl.exec_cmd("swaylock -c 000000 -F")
  hl.exec_cmd("waybar")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd('rm "$HOME/.cache/cliphist/db"')
  hl.exec_cmd("~/scripts/startScratch")
  hl.exec_cmd("vicinae server")

  hl.exec_cmd("tymr --revive")
  hl.exec_cmd("tymr 4pm 'shake'")
  hl.exec_cmd("tymr 5pm 'gym'")

  hl.exec_cmd("easyeffects --gapplication-service")
  hl.exec_cmd("nm-applet --no-agent")
  hl.exec_cmd("~/scripts/blu-notif")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("~/scripts/bat-notif")
  hl.exec_cmd("dotoold")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("LBSync cp")
  hl.exec_cmd("syncthing --no-browser")
  hl.exec_cmd("solaar -b symbolic -w hide")
  hl.exec_cmd("powertop --auto-tune")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("opencode upgrade")
  hl.exec_cmd("pi update")
  hl.exec_cmd('hyprctl setcursor "Bibata-Modern-Classic" 24')
  hl.exec_cmd("zen-browser")
  hl.exec_cmd("[[ $(cat /sys/class/power_supply/BAT*/status) == Discharging ]] || ~/scripts/ytm")

  hl.exec_cmd("~/scripts/vuln-detect")
  -- hl.exec_cmd("~/scripts/lock")
  -- hl.exec_cmd("foot --server")
  -- hl.exec_cmd("swaybg -i $(find ~/wallpapers/ -type f | shuf -n1)")
  -- hl.exec_cmd("~/vtype-players.sh")
  -- hl.exec_cmd("foot -a scratch -e tmux new-session -A -s 'scratch'")
  -- hl.exec_cmd("sleep 1 && tmux send-keys -t scratch.1 'todon' ENTER")
  -- hl.exec_cmd("thorium-browser")
  -- hl.exec_cmd("alacritty --class scratch -e tmux new-session -A -s 'scratch' && sleep 1 && tmux send-keys -t scratch.1 'todon' ENTER")
  -- hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland && nm-applet --indicator")
  -- hl.exec_cmd("wlsunset -l 28.613939 -L 77.209023 -t 50K&")
  -- hl.exec_cmd("[[ $(cat /sys/class/power_supply/BAT0/status) == 'Discharging' ]] && bluetoothctl power off")
  -- hl.exec_cmd("thorium-browser")
  -- hl.exec_cmd("brave --password-store=basic")
  -- hl.exec_cmd("zen-browser")
  -- hl.exec_cmd("spotify")
  -- hl.exec_cmd("line=$(sed -n '3p' /etc/keyd/default.conf); if [[ $line == \\#* ]]; then sudo sed -i '3s/^#//' /etc/keyd/default.conf; fi; sudo keyd reload")
  -- hl.exec_cmd("~/scripts/mouseSim")
  -- hl.exec_cmd("while true;do notify-send -t 10000 PCheck;sleep 5000;done")
  -- hl.exec_cmd("while true;do blu rl;sleep 3;done")
  -- hl.exec_cmd("ulimit -S -u 5000")
  -- hl.exec_cmd("sleep 10 && solaar -w hide")
  -- hl.exec_cmd("~/scripts/fl-alt-passthrough")
  -- hl.exec_cmd('hyprctl setcursor "Banana" 32')
  -- exec = gsettings set org.gnome.desktop.interface cursor-theme "Banana"
  -- hl.exec_cmd('gsettings set org.gnome.desktop.interface cursor-theme "Banana"')
  -- exec = gsettings set org.gnome.desktop.interface cursor-size 32
  -- hl.exec_cmd('gsettings set org.gnome.desktop.interface cursor-size 32')
  -- hl.exec_cmd("antigravity /home/sahaj/projects/tuix")
  -- hl.exec_cmd("env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/8")
  -- hl.exec_cmd("steam steam://rungameid/11561827269651464192")
end)
