-- https://wiki.hypr.land/Configuring/Basics/Autostart/

hl.on("hyprland.start", function()
  hl.exec_cmd("sudo /usr/local/sbin/mute-led")
  hl.exec_cmd("pkill awww-daemon; awww-daemon & sleep 1 && ~/scripts/changeWall rand")
  hl.exec_cmd("swaylock -c 000000 -F")
  hl.exec_cmd("waybar")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("wl-paste --watch cliphist store")
  hl.exec_cmd('rm "$HOME/.cache/cliphist/db"')
  hl.exec_cmd("~/scripts/startScratch")
  hl.exec_cmd("vicinae server")
  hl.exec_cmd("tymr --revive")
  hl.exec_cmd("tymr 4pm 'shake'")
  hl.exec_cmd("tymr 5pm 'gym'")
  hl.exec_cmd("easyeffects --gapplication-service")
  hl.exec_cmd("nm-applet --no-agent")
  hl.exec_cmd("~/scripts/blu-notif")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("~/scripts/bat-notif")
  hl.exec_cmd("dotoold")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("LBSync cp")
  hl.exec_cmd("syncthing --no-browser")
  hl.exec_cmd("solaar -b symbolic -w hide")
  hl.exec_cmd("powertop --auto-tune")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("opencode upgrade")
  hl.exec_cmd('hyprctl setcursor "Bibata-Modern-Classic" 24')
  hl.exec_cmd("zen-browser")
  hl.exec_cmd("[[ $(cat /sys/class/power_supply/BAT*/status) == Discharging ]] || ~/scripts/ytm")
end)

