#!/bin/env bash
textBoxPos="0.9 0.2"

echo "key super+space" | dotoolc
sleep 0.1
echo "mouseto $textBoxPos" | dotoolc
sleep 0.1
echo "click left" | dotoolc
sleep 0.1
echo "key ctrl+a" | dotoolc
sleep 0.01

if [[ $1 == paste ]]; then
  echo "key ctrl+v" | dotoolc
elif [[ $1 == copy ]]; then
  echo 'key ctrl+c' | dotoolc
  sleep 0.01
  echo 'key super+space' | dotoolc
  sleep 0.1
  echo 'key enter' | dotoolc
  sleep 0.01
  echo 'key P' | dotoolc
elif [[ $1 == run ]]; then
  echo "key ctrl+v" | dotoolc
  sleep 0.01
  echo "key ctrl+apostrophe" | dotoolc
  pkill dotoold
  dotoold &
fi
