#!/bin/env bash
file="$1"
size=$(stat -c %s "$file" | numfmt --to=iec --suffix=B)
access_time=$(stat -c %x "$file" | awk '{print $1, $2}' | xargs -I{} date -d "{}" "+%d-%m-%Y %H:%M:%S")
modify_time=$(stat -c %y "$file" | awk '{print $1, $2}' | xargs -I{} date -d "{}" "+%d-%m-%Y %H:%M:%S")
creation_time=$(stat -c %w "$file" | awk '{if ($1 == "-") print "-"; else print $1, $2}' | xargs -I{} date -d "{}" "+%d-%m-%Y %H:%M:%S" 2>/dev/null || echo "-")

purple="\033[34m"
reset="\033[0m"

stat --printf "${purple}File:${reset} %n\n" "$file"
echo -e "${purple}Size:${reset} $size"
echo -e "${purple}Permissions:${reset} %A"
echo -e "${purple}Last Access:${reset} $access_time"
echo -e "${purple}Last Modify:${reset} $modify_time"
echo -e "${purple}Creation:${reset} $creation_time"
echo -e "${purple}Owner:${reset} %U"
echo -e "${purple}Group:${reset} %G"
echo -e "${purple}Type:${reset} %F"
echo -e "${purple}Links:${reset} %h"
