#!/bin/env bash

# usage: (jour, jour -1, jour w 2, etc.)
offset=0
type=d

if [[ $1 =~ ^[dwmy]$ ]]; then
  type=$1
  shift
fi

if [[ $1 =~ ^[+-]?[0-9]+$ ]]; then
  offset=$1
fi

case "$type" in
d)
  desired_date=$(date -d "$offset days" +"%F")
  subpath="daily"
  ;;
w)
  desired_date=$(date -d "$offset weeks" +"%Y-W%V")
  subpath="weekly"
  ;;
m)
  desired_date=$(date -d "$offset months" +"%Y-%m")
  subpath="monthly"
  ;;
y)
  desired_date=$(date -d "$offset years" +"%Y")
  subpath="yearly"
  ;;
esac

file_path="$HOME/notes/journal/$subpath/$desired_date.md"
template_path="$HOME/notes/journal/template/$subpath.md"

if [ ! -f "$file_path" ]; then
  cat "$template_path" >"$file_path"
fi
nvim "$file_path"
