#!/bin/env bash
package_list=$(pacman -Ss | awk -F '/' '{print $2}' | awk '{print $1}' | sort)
packages=$(echo "$package_list" | fzf --multi --preview 'pacman -Si {}' --layout=reverse --query="'")
packages=$(echo "$packages" | tr '\n' ' ' | sed 's/[[:space:]]*$//')
if [ "$packages" != "" ]; then
  echo -ne "sudo pacman -Syu --needed $packages\nExecute?(Y/n/no(c)onfirm)"
  read -r yn
  if [[ "$yn" == "y" ]] || [[ "$yn" == "" ]]; then
    sudo pacman -Syu --needed $(echo $packages)
  elif [[ "$yn" == "c" ]]; then
    sudo pacman -Syu --needed --noconfirm $(echo $packages)
  fi
fi
