#!/bin/env bash

if [[ $(wl-paste --list-types) != *"image/png"* ]]; then
  notify-send -t 1500 "No image in clipboard"
  exit 1
fi

path=$(yad --file --save --filename="ss.png")
if [ -z "$path" ]; then
  notify-send -t 1500 "Cancelled"
  exit 1
fi

wl-paste >"$path"
notify-send -t 1500 "$path" --icon="$path"
