#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(
    (
      find ~/projects -mindepth 1 -maxdepth 1 -type d
      find ~/projects -mindepth 2 -maxdepth 2 -type d \( -name frontend -o -name backend -o -name shared \)
    ) | sed "s|$HOME|~|" | fzf | sed "s|~|$HOME|"
  )
fi

if [[ -z $selected ]]; then
  exit 0
fi

# If selected path ends with frontend/backend/shared, use last two dirs, else just basename
case "$selected" in
*/frontend | */backend | */shared)
  parent_dir=$(basename "$(dirname "$selected")")
  child_dir=$(basename "$selected")
  selected_name="${parent_dir}_${child_dir}"
  ;;
*)
  selected_name=$(basename "$selected" | tr . _)
  ;;
esac

selected_name=$(echo "$selected_name" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected"
  exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
  tmux attach-session -t "$selected_name"
else
  tmux switch-client -t "$selected_name"
fi
