#!/bin/env bash
# modified version of https://gist.github.com/gingkapls/33f7567900a32ceed4b27f0eae1ffcd8

# active=$(pamixer --list-sources | grep -v "Suspended" | head -n1 | awk '{print $2}' | tr -d '"')

videoDir=~/Videos
active=$(pactl get-default-sink).monitor
mkdir -p $videoDir

filename=$(date +%F_%T.mp4)

echo active sink: $active
echo $filename

if [ -z $(pgrep wf-recorder) ]; then
  if [ "$1" == "-s" ]; then
    # wf-recorder -f $videoDir/$filename -a -g "$(slurp)" >/dev/null 2>&1 &
    wf-recorder -f $videoDir/$filename -a="$active" -g "$(slurp)" >/dev/null 2>&1 &
    while [ -n "$(pgrep -x slurp)" ]; do
      sleep 0.5
    done
    sleep 2
    pkill -RTMIN+8 waybar
  else
    # wf-recorder -f $videoDir/$filename -a >/dev/null 2>&1 &
    wf-recorder -f $videoDir/$filename -a="$active" >/dev/null 2>&1 &
    pkill -RTMIN+8 waybar
  fi
else
  killall -s SIGINT wf-recorder
  notify-send -t 1000 "Recording Stopped"
  while [ -n "$(pgrep -x wf-recorder)" ]; do wait; done
  pkill -RTMIN+8 waybar
  name="$(zenity --entry --text "enter recording filename" --cancel-label="Delete")"
  case $? in
  0)
    if [ -n "$name" ]; then
      latest_file=$(ls -t $videoDir/*.mp4 | head -n1)
      extension="${latest_file##*.}"
      dir_path=$(dirname "$latest_file")
      mv "$latest_file" "$dir_path/${name}.${extension}"
    fi
    ;;
  1)
    latest_file=$(ls -t $videoDir/*.mp4 | head -n1)
    trash-put "$latest_file"
    notify-send -t 2000 "Recording Trashed"
    ;;
  esac
fi
