#!/bin/env bash
if [[ "$1" == "" ]];then
    echo "search argument required"
else
    aur_package_list=$(yay -Ss "$1" | awk 'NR % 2 == 1' | tac);
    selected_package=$(echo "$aur_package_list" | fzf --layout=reverse --query="'");
    if [ "$selected_package" != "" ];then
        packname=$( echo "$selected_package" | awk -F/ '{print $2}' | awk '{print $1}' )
        echo -ne "yay -S $packname \nExecute?(Y/n)"
        read yn;
        if [[ "$yn" == "y" ]] || [[ "$yn" == "" ]];then
            yay -S "$packname"
        fi
    fi
fi
