#!/bin/bash

outfile=~/bdevices.log
blacklistFile=~/bblacklist.log

bluetoothctl --timeout 99999 scan on | while read -r line; do
  mac=$(echo "$line" | awk '{print $3}')
  if grep -q "$mac" "$blacklistFile" || ! [[ $mac =~ ([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$ ]]; then
    continue
  fi
  if ! grep -q "$mac" "$outfile"; then
    echo "$line" | awk '{print $3,$4}' >>"$outfile"
    echo "New device added: $line"
  fi
done
